#!/bin/csh -f

## This script makes all of the SMOKE programs

#
## Set controllers for turning on/off library building
#
setenv SMK_MAKE_LIB     N   # [ Y | N ]
setenv SMK_MAKE_MOBLIB  N   # [ 5A | 5B | 6 | N ]

#
## Set the directory for the sysflags and smk_mkdir scripts
#

set assigndir = ../../assigns
if ( $?M3MODEL ) then
   set assigndir = $M3MODEL/smoke/assigns

else

   if ( $?SMKROOT ) then
      set assigndir = $SMKROOT/assigns
   endif

endif

#
## Source the sysflags script to set environment variables for compiling
#

if ( ! -e $assigndir/sysflags ) then
   echo "Cannot find sysflags file\!"
   echo " "
   echo "Get set up for Models-3, EDSS, or set SMKROOT to the"
   echo "   path of the Assigns file."
   exit( 1 )
else

   source $assigndir/sysflags

endif

#
## Create the directories
#
$assigndir/smk_mkdir

#
## Interpret the script argument
#

set what = $argv

#
## Make SMOKE library
#
if ( $?SMK_MAKE_LIB ) then

   if ( $SMK_MAKE_LIB == 'Y' ) then
      echo "Building SMOKE library..."
      cd $MD_SRC
      make clean
      cd $EL_SRC
      make clean
      Makeit $argv
   endif

endif

#
## Make Mobile5b library, if requested
#
if ( $?SMK_MAKE_MOBLIB ) then

   if ( $SMK_MAKE_MOBLIB == '5A' ) then
      echo 'NOTE: Mobile5a library build not supported in this version'
   endif 

   if ( $SMK_MAKE_MOBLIB == '5B' ) then
      echo "Building Mobile5b library..."
      cd $M5_SRC
      make $argv
   endif 

   if ( $SMK_MAKE_MOBLIB == '6' ) then
      echo 'NOTE: Mobile6 library build not supported in this version'
      
   endif

endif

#
## Make main programs
#
echo "Building Smkinven..."
cd $IV_SRC     # Smkinven
make clean
Makeit $argv    

echo "Building Spcmat..."
cd $SP_SRC     # Spcmat
make clean
Makeit $argv    

echo "Building Grdmat..."
cd $GD_SRC     # Grdmat
make clean
Makeit $argv    

echo "Building Cntlmat..."
cd $CL_SRC     # Cntlmat
make clean
Makeit $argv

echo "Building Temporal..."
cd $TM_SRC     # Temporal
make clean
Makeit $argv    

echo "Building Rawbio and Tmpbio..."
cd $BG_SRC    # Rawbio and Tmpbio
make clean
Makeit $argv

echo "Building Premobl and Emisfac..."
cd $MB_SRC     # Premobl and Emisfac
make clean
Makeit $argv    

echo "Building Elevpoint and Laypoint..."
cd $PT_SRC     # Elevpoint and Laypoint
make clean
Makeit $argv

echo "Building Smkmerge and Mrggrid..."
cd $MG_SRC     # Smkmerge and Mrggrid
make clean
Makeit $argv

echo "Building Utilities..."
cd $UT_SRC     # Smk2emis and Uam2ncf
make clean
Makeit $argv

echo "Building Quality Assurance..."
cd $QA_SRC     # Smkreport
make clean
Makeit $argv


exit( 0 )

