#!/bin/csh -f

# Extract "debug" from arguments, if needed

# Set number of iterations
set iter = $#argv

# Loop through arguments

# Make all code for argument list
if ( $iter > 0 ) then

   set i = 0
   while ( $i < $iter )

      @ i = $i + 1

      # Determine if this is a debug executable to build or not
      echo $argv[$i] | grep debug
      if ( ! $status ) then
          set testval = debug
      else
          set testval = optimized
      endif  

      # Change compiler flags depending on debug or not
      switch( $testval )

      # Compile for debug case
      case debug:
         set fsav = ( $FFLAGS )
         set m6sav = ( $M6_FFLAGS )
         setenv FFLAGS "$DBGFLAGS"
         setenv M6_FFLAGS "$DBGFLAGS"
         make $argv[$i]
         setenv FFLAGS "$fsav"
         setenv M6_FFLAGS "$m6sav"
         breaksw

      # Compile for optimized case
      default:
         make $argv[$i]
         breaksw
      endsw

   end

# Make all optimized code
else
   make all

endif

