#!/bin/csh -f

# This script checks to see if the SMOKE installation worked successfully

set errfile = $SCRIPTS/install/.err
set errstat = 0

set repdir = $SMKROOT/doc/checkdemo/reports
set fyrepdir = $REPORTS/nctox_18/scenario

# Check stationary area sources
echo 'Stationary area source differences' > $errfile

diff $REPSCEN/repagts_l.*0710* $repdir/repagts_l.*.nctox.* >> $errfile
if ( $status > 0 ) then
    set errstat = 1
endif

diff $fyrepdir/repagts_l.*0710* $repdir/repagts_l.*.nctox_18.* >> $errfile
if ( $status > 0 ) then
    set errstat = 1
endif

# Check biogenic sources
echo 'Biogenic source differences' >> $errfile

diff $REPSCEN/repb3gts_s.*0710* $repdir/repb3gts_s.*.nctox.* >> $errfile
if ( $status > 0 ) then
    set errstat = 1
endif

# Check mobile sources
echo 'Mobile source differences' >> $errfile

diff $REPSCEN/repmgts_l.*0710* $repdir/repmgts_l.*.nctox.* >> $errfile
if ( $status > 0 ) then
    set errstat = 1
endif

diff $fyrepdir/repmgts_l.*0710* $repdir/repmgts_l.*.nctox_18.* >> $errfile
if ( $status > 0 ) then
    set errstat = 1
endif

# Check nonroad area sources
echo 'Nonroad source differences' >> $errfile

diff $REPSCEN/repngts_l.*0710* $repdir/repngts_l.*.nctox.* >> $errfile
if ( $status > 0 ) then
    set errstat = 1
endif

diff $fyrepdir/repngts_l.*0710* $repdir/repngts_l.*.nctox_18.* >> $errfile
if ( $status > 0 ) then
    set errstat = 1
endif

# Check point sources
echo 'Point source differences' >> $errfile

diff $REPSCEN/reppgts_l.*0710* $repdir/reppgts_l.*.nctox.* >> $errfile
if ( $status > 0 ) then
    set errstat = 1
endif

diff $fyrepdir/reppgts_l.*0710* $repdir/reppgts_l.*.nctox_18.* >> $errfile
if ( $status > 0 ) then
    set errstat = 1
endif

# Make sure all programs completed successfully
set num_log_file = `ls $LOGS | wc -l`
set sav_dir = `pwd`
cd $LOGS
set num_success = `grep 'Normal Completion' * | wc -l`
if( $num_log_file != $num_success ) then
   echo ' '
   echo 'All programs in your installation did not complete successfully\!'
   echo 'Please look at the log files in $LOGS for more information.'
   echo ' '
endif
cd $sav_dir

if ( $errstat != 0 ) then
   mv $errfile $SMKROOT/doc/install_diffs.txt
   echo ' '
   echo 'Differences between your installation and correct answers exist\!'
   echo 'Please refer to file $SMKROOT/doc/install_diffs.txt for details.'
   echo ' '
else
   echo ' '
   echo 'No differences found between your SMOKE report files and the comparison files.'
   echo 'Your installation and example SMOKE run have completed successfully\!'
   echo ' '
   rm -rf $errfile
endif
