C Version "@(#)$Id$ $Source$ $Date$ 

C
C  RSDINF contains the variables that holds the value for the
C         Remote Sensing Device (RSD) program 
C
C  Common Block Dictionary:
C
C   Name    Type                  Description
C  ------   ----  -----------------------------------------------------
C  RSDFLG    I    Flag that indicate RSD  Program  
C
C  Notes:
      INTEGER RSDFLG
      COMMON /RSDINF/ RSDFLG
