#!/bin/csh -fx

# Input files (netCDF) from SMOKE Tool

setenv BGPRO_A $GE_DAT/t2_36_c_landa.ioapi
setenv BGPRO_B $GE_DAT/t2_36_c_landb.ioapi
setenv BGPRO_TOT $GE_DAT/t2_36_c_totals.ioapi

# Input file (ASCII) xref file

setenv B3XRF $GE_DAT/b3tob2B.xrf

# Output file which can be input into Rawbio

if ( ! -e $BGDAT ) then
   mkdir -p $BGDAT
endif

setenv BGUSE $BGDAT/t2_36_c.beld3to2.txt


$SMK_BIN/beld3to2
