#!/bin/csh -f

   ### Set umask to be group writable, world read and execute
   umask 2

   ### Make input and output director(ies) #######
   if ( -e $SMKDAT ) then
       if( ! -e $INVDIR ) mkdir -p $INVDIR
       if( ! -e $INVOPD ) mkdir -p $INVOPD
       if( ! -e $A_OUT )  mkdir -p $A_OUT
       if( ! -e $B_OUT )  mkdir -p $B_OUT
       if( ! -e $M_OUT )  mkdir -p $M_OUT
       if( ! -e $P_OUT )  mkdir -p $P_OUT
       if( ! -e $OUTPUT ) mkdir -p $OUTPUT
       if( ! -e $STATIC ) mkdir -p $STATIC
       if( ! -e $BASDIR ) mkdir -p $BASDIR
       if( ! -e $REPSCEN ) mkdir -p $REPSCEN
       if( ! -e $REPSTAT ) mkdir -p $REPSTAT
       if( ! -e $REPSTAT ) mkdir -p $REPSTAT
       if( ! -e $REPORTS/$ASCEN/$ESDATE ) mkdir -p $REPORTS/$ASCEN/$ESDATE
       if( ! -e $REPORTS/$ASCEN/static )  mkdir -p $REPORTS/$ASCEN/static
       if( ! -e $REPORTS/$BSCEN/$ESDATE ) mkdir -p $REPORTS/$BSCEN/$ESDATE
       if( ! -e $REPORTS/$MSCEN/$ESDATE ) mkdir -p $REPORTS/$MSCEN/$ESDATE
       if( ! -e $REPORTS/$MSCEN/static )  mkdir -p $REPORTS/$MSCEN/static
       if( ! -e $REPORTS/$PSCEN/$ESDATE ) mkdir -p $REPORTS/$PSCEN/$ESDATE
       if( ! -e $REPORTS/$PSCEN/static )  mkdir -p $REPORTS/$PSCEN/static
  else
       echo "ERROR: Create the SMOKE data directory\!"
       exit( 1 )
   endif

   ### Check permissions on output directories ####
   set user = `whoami`
   foreach dir ( $INVDIR $INVOPD $SCENARIO $STATIC $A_OUT $B_OUT $M_OUT \
                 $P_OUT $OUTPUT $BASDIR $REPORTS/$ASCEN $REPORTS/$BSCEN \
                 $REPORTS/$MSCEN $REPORTS/$PSCEN $REPSCEN $REPSTAT )

       set line   = ( `/bin/ls -ld $dir` )
       set owner  = $line[3]
       set check  = ( `echo $line | grep $user` )
       if ( $status == 0 ) then

           set permis = ( `echo $line | grep drwxrw` )
           if( $status != 0 ) then
               chmod ug+w $dir
           endif

       else

           set permis = ( `echo $line | grep drwxrw` )
           if ( $status != 0 ) then
               echo "NOTE: Do not have write permission for directory"
               echo "      $dir"
               echo "      Check with user $owner for write permissions"
           endif

       endif

   end

   cd $ASSIGNS
