#!/bin/csh -f

#  %W% %P% %G% %U%

#  Determine operating system for compiling SMOKE
source $EDSS_ROOT/scripts/platform

if ( $status != 0 ) then
    exit( $status )
endif

source $EDSS_SUBSYS/edss_tools/setup/set_dirs.scr
source $EDSS_SUBSYS/filesetapi/Setup

# Make directories for library, object files, and executables
setenv    SMK_BIN "$SMKROOT/$EDSS_EXE"
setenv    IOAPIDIR $EDSS_SUBSYS/ioapi/bin/$EDSS_EXE
setenv    NETCDFDIR $EDSS_SUBSYS/netcdf/bin/$EDSS_EXE
if( ! -e $SMK_BIN ) mkdir -p $SMK_BIN
if( ! -e $MD_SRC/$EDSS_EXE ) mkdir -p $MD_SRC/$EDSS_EXE
if( ! -e $IOAPIDIR ) mkdir -p $IOAPIDIR
if( ! -e $NETCDFDIR ) mkdir -p $NETCDFDIR

if ( $?M6_FFLAGS ) then
else
   echo "ERROR: The platform file in EDSS_ROOT/scripts has not been"
   echo "       updated to include the M6_FFLAGS compiler variable"
   exit( 1 )
endif

setenv LIBS_COMPILE " "

switch ( $EDSS_EXE )
  case IRIXn32f90:
  case IRIX6f90:
  case IRIXn64f90:
    setenv FC    f90
    setenv FFLAGS   "$FFLAGS -I${IOINC} -I${INC} -I${MD_SRC}/${EDSS_EXE} -I${ETDSRC}/${EDSS_EXE} -I${FS_ROOT} -I${FS_BIN}"
    setenv DBGFLAGS "$DBGFLAGS -I${IOINC} -I${INC} -I${MD_SRC}/${EDSS_EXE} -I${ETDSRC}/${EDSS_EXE} -I${FS_ROOT} -I${FS_BIN}"
    setenv LDIRS    "-L${SMK_BIN} -L${TOOLS_BIN} -L${FS_BIN} -L${IOAPIDIR} -L${NETCDFDIR}"
    setenv LIBS_SYS    "-lsmoke -lfileset -ledsstools -lioapi -lnetcdf -lmp"
    setenv LIBS_DEBUG_SYS "-lsmoke.debug -lfileset.debug -ledsstools.debug -lioapi.debug -lnetcdf.debug -lmp"
    breaksw
  case SunOS5f90:
#   NOTE: -Bstatic caused problems with ENVYN (perhaps because not
#         using I/O API compiled with f90 ?)
    setenv FC    f90
    setenv FFLAGS   "$FFLAGS  -M${MD_SRC}/${EDSS_EXE} -M${ETDSRC}/${EDSS_EXE}  -M${FS_BIN} -I${IOINC} -I${INC} -I${FS_ROOT}"
    setenv DBGFLAGS "$DBGFLAGS -M${MD_SRC}/${EDSS_EXE} -M${ETDSRC}/${EDSS_EXE} -M${FS_BIN} -I${IOINC} -I${INC} -I${FS_ROOT} "
    setenv LDIRS    "-L${SMK_BIN} -L${TOOLS_BIN} -L${FS_BIN} -L${IOAPIDIR} -L${NETCDFDIR}"
    setenv LIBS_SYS     "-lsmoke -lfileset -ledsstools -lioapi -lnetcdf"
    setenv LIBS_DEBUG_SYS "-lsmoke.debug -fileset.debug -ledsstools.debug -lioapi.debug -lnetcdf.debug"
    breaksw
case HP_UX11f90:
    setenv FC  f90
    setenv FFLAGS   "$FFLAGS  -I${IOINC} -I${INC} -I${MD_SRC}/${EDSS_EXE} -I${ETDSRC}/${EDSS_EXE} -I${FS_ROOT} -I${FS_BIN}"
    setenv DBGFLAGS "$DBGFLAGS -I${IOINC} -I${INC} -I${MD_SRC}/${EDSS_EXE} -I${ETDSRC}/${EDSS_EXE} -I${FS_ROOT} -I${FS_BIN}"
    setenv LDIRS    "+U77 -Wl,-L,${SMK_BIN},${TOOLS_BIN},${FS_BIN},${IOAPIDIR},${NETCDFDIR}"
    setenv LIBS_SYS     "-lsmoke -lfileset -ledsstools -lioapi -lnetcdf"
    setenv LIBS_DEBUG_SYS "-lsmoke.debug -lfileset.debug -ledsstools.debug -lioapi.debug -lnetcdf.debug"
    breaksw
case AIX4n64f90:
case AIX4f90:
    setenv FC  xlf
    setenv FFLAGS   "$FFLAGS -DDBLBSLASH -I${IOINC} -I${INC} -I${MD_SRC}/${EDSS_EXE}" -I${ETDSRC}/${EDSS_EXE} -I${FS_ROOT} -I${FS_BIN}"
    setenv DBGFLAGS "$DBGFLAGS -DDBLBSLASH -I${IOINC} -I${INC} -I${MD_SRC}/${EDSS_EXE}" -I${ETDSRC}/${EDSS_EXE} -I${FS_ROOT} -I${FS_BIN}"

    setenv LDIRS    "-L${SMK_BIN} -L${TOOLS_BIN} -L${FS_BIN} -L${IOAPIDIR} -L${NETCDFDIR} -lxlsmp"
    setenv LIBS_SYS     "-lsmoke -lfileset -ledsstools -lioapi -lnetcdf"
    setenv LIBS_DEBUG_SYS "-lsmoke.debug -lfileset.debug -ledsstools.debug -lioapi.debug -lnetcdf.debug"
    breaksw
case Linux2_alpha:
    setenv FC  fort
    setenv FFLAGS   "$FFLAGS -I${IOINC} -I${INC} -I${MD_SRC}/${EDSS_EXE} -I${ETDSRC}/${EDSS_EXE} -I${FS_ROOT} -I${FS_BIN}"
    setenv DBGFLAGS "$DBGFLAGS -I${IOINC} -I${INC} -I${MD_SRC}/${EDSS_EXE} -I${ETDSRC}/${EDSS_EXE} -I${FS_ROOT} -I${FS_BIN}"
    setenv LDIRS    "-L${SMK_BIN} -L${TOOLS_BIN} -L${FS_BIN} -L${IOAPIDIR} -L${NETCDFDIR}"
    setenv LIBS_SYS     "-lsmoke -lfileset -ledsstools -lioapi -lnetcdf"
    setenv LIBS_DEBUG_SYS "-lsmoke.debug -lfileset.debug -ledsstools.debug -lioapi.debug -lnetcdf.debug"
    breaksw
case Linux2_x86ifc:
    setenv FC  ifc
    setenv FFLAGS   "$FFLAGS -DDBLBSLASH -I${ETINC} -I${IOINC} -I${INC} -I${FS_ROOT} -I${MD_SRC}/${EDSS_EXE} -I${ETDSRC}/${EDSS_EXE}"
    setenv DBGFLAGS "$DBGFLAGS -DDBLBSLASH -I${ETINC} -I${IOINC} -I${INC} -I${FS_ROOT} -I${MD_SRC}/${EDSS_EXE} -I${ETDSRC}/${EDSS_EXE}"
    setenv LDIRS    "-static -L${SMK_BIN} -L${TOOLS_BIN} -L${FS_BIN} -L${IOAPIDIR} -L${NETCDFDIR}"
    setenv LIBS_SYS     "-lsmoke -lfileset -ledsstools -lioapi -lnetcdf"
    setenv LIBS_DEBUG_SYS "-lsmoke.debug -lfileset.debug -ledsstools.debug -lioapi.debug -lnetcdf.debug"
    setenv LIBS_COMPILE "-lPEPCF90"
    breaksw
case  Linux2_x86pg:
    setenv FC  pgf90
    setenv FFLAGS   "$FFLAGS  -module ${MD_SRC}/${EDSS_EXE} -module ${ETDSRC}/${EDSS_EXE} -module ${FS_BIN} -I${ETINC} -I${IOINC} -I${INC} -I${MD_SRC}/${EDSS_EXE} -I${ETDSRC}/${EDSS_EXE} -I${FS_ROOT} -I${FS_BIN}"
    setenv DBGFLAGS "$DBGFLAGS  -module ${MD_SRC}/${EDSS_EXE} -module ${ETDSRC}/${EDSS_EXE} -module ${FS_BIN} -I${ETINC} -I${IOINC} -I${INC} -I${MD_SRC}/${EDSS_EXE} -I${ETDSRC}/${EDSS_EXE} -I${FS_ROOT} -I${FS_BIN}"
    setenv LDIRS    "-L${SMK_BIN} -L${TOOLS_BIN} -L${FS_BIN} -L${IOAPIDIR} -L${NETCDFDIR}"
    setenv LIBS_SYS     "-lsmoke -lfileset -ledsstools -lioapi -lnetcdf"
    setenv LIBS_DEBUG_SYS "-lsmoke.debug -lfileset.debug -ledsstools.debug -lioapi.debug -lnetcdf.debug"
    breaksw
default:
    echo "The sysflags file in the ASSIGNS directory does not have compiler"
    echo "    settings for executable format "$EDSS_EXE
    echo "Pleae edit the sysflags file and add this exectuable format and the"
    echo "    appropriate compiler settings."
    exit( 2 )
endsw

switch ( $EDSS_EXE )
case Linux2_x86ifc:
    setenv M6_FFLAGS "$M6_FFLAGS -I${ETINC} -I${IOINC} -I${INC} -I${FS_ROOT}"
    breaksw
default:
    setenv M6_FFLAGS "$FFLAGS"
endsw

echo " "
echo "Host name:             "`hostname`
echo "Platform type:         $EDSS_EXE"
echo "Main SMOKE directory:  $SMKROOT"
echo "Executable directory:  $SMK_BIN"
echo "Data directory:        $SMKDAT"
echo " "
